### ISSUE TITLE
No navpage 

### ISSUE THREAD

**Issue by shbIOS** [vczero/weex-yy#1]
你好，我按照你给定的步骤，将文件集成了，但是显示不出 navpage，不知道为什么，难道要单独安装 weex-compents 组件么？谢谢
![2016-08-31 2 25 21](https://cloud.githubusercontent.com/assets/7531102/18118370/e6ffd542-6f86-11e6-9492-e8f8919db118.png)

**Comment by vczero** [comment]
这个navpage我在代码中去掉了。具体可参见：https://github.com/vczero/weex-yy/tree/c0485f70c73ab2ff923fc5f642c848acdcb76eea中之前提交的代码记录。navpage等都是我自行改造的。

**Comment by vczero** [comment]
如果使用的是playground，则就会有头部。
