### ISSUE TITLE
项目创建

### ISSUE THREAD

**Issue by emptywalker** [vczero/weex-yy#2]
1.这个项目是相当于在weex本身的项目中进行替换的， 我想知道你在创建这个项目时，是自己初始化的新项目还是就在weex仓库中就行修改的啊？
PS：问这个问题主要是，我在实现weex的时候是自己weex init的这个项目 -> 编写的we文件 -> 再移到自己的Xcode项目中， 发现你的做法更加省事儿，就想知道在创建新的项目时，怎么样比较合理些

2.我发现这个项目在iOS真机上跑起来的时候，所有的二级界面都没有导航条的。

**Comment by vczero** [comment]
1. 自己初始化项目，然后移植到weex仓库底下验证。  当然，可以做的是：将weex仓库下打包文件全部拷贝过来修改成自己需要的即可。
2. 这个是我故意去掉的，有兴趣的可以添加上，提交一个新分支。欢迎pr, :)

**Comment by emptywalker** [comment]
@vczero  可以，我也仿照了你的方式，实现了一个小项目，我会慢慢的在里面加入的，https://github.com/emptywalker/PurchasingPlatform  这是我做的，上次的那个动态添加的问题也解决了

**Comment by vczero** [comment]
很赞
